
name: CI-Test Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"


      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra


      - name: Make Directory for results
        run: mkdir -p testResults


      - name: Run POSTMAN collection
        run: |
          newman run ./PostmanCollections/googleplace.json" e ./Test.postman_environment.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darkTheme  > testResults/runreport1.html


      - name: Output the run Details
        uses: actions/upload-artifact@v2
        with:
          name: RunReports
          path: testResults
